spring:

  profiles:
    active: local

  ############## DB연결 ( mysql )
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.192.148.204:3306/system_failure_mgnt?useSSL=false&characterEncoding=utf8&serverTimezone=UTC&useSSL=false&useUnicode=true
    username: devcomm
    password: devcomm1234



    ############## 테스트용 데이터설정 H2 데이터베이스
    #url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL

  #jpa 설정
  jpa:
    database: mysql
    generate-ddl: true
    show-sql: true

    #mysql mode로 변경
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

  # js 절대경로 설정
  mvc:
    static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static

    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: create


  # view resolver
  thymeleaf:
    prefix: classpath:templates/
    cache: false

  # 개발 - js나 html 수정 시 바로 반영
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false


  #    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
  h2:
    console:
      enabled: true
      path: /h2-console
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true



server:
  port: 8888


# logging
logging:
  config: classpath:logback-local.xml

