spring:

  # js 절대경로 설정
  mvc:
    static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static

  # db관련
  #jpa 설정
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    generate-ddl: true
  thymeleaf:
    prefix: classpath:templates/
    cache: false

  profiles:
    active: local

  # 개발 - js나 html 수정 시 바로 반영
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false

  #mysql mode로 변경
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://119.192.148.204:3306/system_failure_mgnt?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
      username: devcomm
      password: devcomm1234
      driver-class-name: com.mysql.jdbc.Driver


  #    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
#    hikari:
#      jdbc-url: jdbc:mysql://119.192.148.204:3306/system_failure_mgnt?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#      username: devcomm
#      password: devcomm1234


server:
  port: 8888


# logging
logging:
  config: classpath:logback-local.xml

