spring:
  profiles:
    active: local

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    prefix: classpath:templates/
    cache: false

server:
  port: 8888
